name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and Push Docker Image to GHCR
      - name: Build and Push Docker Image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/automated-researcher:latest
          docker push ghcr.io/${{ github.repository_owner }}/automated-researcher:latest
